import { createContext, useContext, useState, type ReactNode } from "react";

export type Language = "ro" | "ru" | "en";

const translations = {
  ro: {
    nav: {
      dashboard: "Dashboard",
      specialists: "Specialiști",
      evaluations: "Evaluări",
      reports: "Rapoarte",
      settings: "Setări",
      logout: "Deconectare",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Privire de ansamblu asupra performanței echipei.",
      totalEvals: "Total evaluări",
      avgScore: "Scor mediu echipă",
      weakestSection: "Etapa cea mai slabă",
      bestSection: "Etapa cea mai bună",
      monthlyTrend: "Evoluție lunară",
      recentEvals: "Evaluări recente",
      recentDesc: "Ultimele",
      recentDesc2: "evaluări adăugate.",
      sectionPerformance: "Performanța pe compartimente",
      noData: "Nu există date suficiente.",
      noRecent: "Nu există evaluări recente.",
      monthlyProgress: "Progres lunar",
      target: "Țintă",
      evalsPerMonth: "evaluări/lună",
      from: "De când",
      to: "Până când",
      trendFrom: "De la",
      trendTo: "Până la",
      noDataInterval: "Nu există date în intervalul selectat.",
      editTarget: "Editează ținta lunară",
      setTarget: "Setați ținta lunară",
      lowPerformers: "Specialiști cu scor mediu < 70",
      noLowPerformers: "Nu există specialiști sub performanță.",
      allEvals: "Toate evaluările",
      noEvalsInterval: "Nu există evaluări în intervalul selectat.",
      noChanges: "Fără schimbări",
      score: "Scor",
    },
    specialists: {
      title: "Specialiști",
      subtitle: "Gestionați echipa de specialiști.",
      add: "Adaugă specialist",
      archiveBtn: "Arhivați",
      archived: "Arhivat",
      active: "Activi",
      noSpecialists: "Nu există specialiști.",
      profile: "Profil",
      evaluate: "Evaluează",
      name: "Nume",
      position: "Funcție",
      department: "Departament",
      spiScore: "Scor SPI",
      evals: "Evaluări",
      status: "Status",
      actions: "Acțiuni",
      archiveConfirm: "Arhivezi specialistul?",
      archiveDesc: "Specialistul va fi mutat în arhivă și nu va mai apărea în listele active.",
      firstName: "Prenume",
      lastName: "Nume",
      cancel: "Anulare",
      save: "Salvează",
      addTitle: "Adaugă specialist nou",
    },
    evaluations: {
      title: "Evaluări",
      subtitle: "Lista tuturor evaluărilor realizate în sistem.",
      new: "Evaluare nouă",
      specialist: "Specialist",
      dateTime: "Data & Ora",
      client: "Client",
      type: "Tip",
      status: "Status",
      score: "Scor",
      view: "Vezi",
      edit: "Editează",
      delete: "Șterge",
      finalized: "Finalizat",
      draft: "Draft",
      noEvals: "Nu s-au găsit evaluări.",
      search: "Caută după specialist sau client...",
      deleteConfirm: "Șterge evaluarea?",
      deleteDesc: "Această acțiune este ireversibilă. Evaluarea draft pentru",
      deleteDesc2: "va fi ștearsă definitiv.",
      cancel: "Anulare",
      excellent: "Excelent",
      good: "Bun",
      poor: "Slab",
    },
    newEval: {
      title: "Evaluare nouă",
      editTitle: "Editează draft",
      details: "Detalii apel / întâlnire",
      specialistLabel: "Specialist *",
      clientLabel: "Client *",
      dateLabel: "Data",
      timeLabel: "Ora",
      typeLabel: "Tip evaluare",
      evaluatorLabel: "Evaluator",
      typeCall: "Apel",
      typeMeeting: "Întâlnire",
      typeChat: "Chat",
      clientPlaceholder: "Nume client",
      criteriaTitle: "Criterii de evaluare",
      weight: "Pondere",
      scoreCard: "Scor evaluare",
      total: "Total",
      excellent: "Excelent",
      good: "Bun",
      poor: "Slab",
      levelGood: "Bun (100%)",
      levelMedium: "Mediu (60%)",
      levelPoor: "Slab (0%)",
      observations: "Observații (opțional)",
      audio: "Atașează înregistrare (opțional)",
      selectAudio: "Selectează fișier audio",
      finalize: "Finalizează evaluarea",
      saveDraft: "Salvează draft",
      saveChanges: "Salvează modificările",
      leaveTitle: "Părăsiți pagina?",
      leaveDesc: "Toate datele nesalvate vor fi pierdute.",
      leave: "Părăsește",
      cancel: "Anulare",
      requiredFields: "Completați câmpurile obligatorii",
      requiredDesc: "Specialist și client sunt obligatorii.",
      audioError: "Audio nu a putut fi atașat",
      saveError: "Eroare la salvare",
      saveErrorDesc: "Vă rugăm încercați din nou.",
      finalized: "Evaluare finalizată",
      draftSaved: "Draft salvat",
      selectSpecialist: "Selectează specialist",
      obtainedScore: "Punctaj obținut",
    },
    evalDetail: {
      title: "Detalii evaluare",
      finalized: "Finalizată",
      draft: "Draft",
      specialist: "Specialist",
      evaluator: "Evaluator",
      date: "Data",
      clientType: "Client / Tip",
      audio: "Înregistrare audio",
      totalScore: "Scor Total",
      criteria: "Criterii evaluate",
      levelGood: "Bun (100%)",
      levelMedium: "Mediu (60%)",
      levelPoor: "Slab (0%)",
      weight: "Pondere",
      obtainedScore: "Punctaj obținut",
      observations: "Observații",
      editDraft: "Editează draft",
      unavailable: "Evaluare indisponibilă",
      excellent: "Excelent",
      good: "Bun",
      poor: "Slab",
      average: "mediu",
    },
    profile: {
      avgScore: "Scor mediu",
      evalCount: "Număr evaluări",
      bestSection: "Etapa cea mai bună",
      worstSection: "Etapa cea mai slabă",
      evolution: "Evoluție (6 luni)",
      skills: "Competențe",
      spiScore: "Scor SPI",
      evaluate: "Evaluează",
      history: "Istoric evaluări",
      historyDesc: "Toate evaluările realizate pentru",
      noEvals: "Nicio evaluare înregistrată.",
      noData: "Nu există date.",
      radarMin: "Sunt necesare cel puțin 3 categorii pentru vizualizarea radar.",
      date: "Data",
      client: "Client",
      type: "Tip",
      status: "Status",
      finalized: "Finalizat",
      draft: "Draft",
      excellent: "Excelent",
      good: "Bun",
      poor: "Slab",
      score: "Scor",
    },
    reports: {
      title: "Rapoarte și Analize",
      subtitle: "Statistici detaliate privind calitatea apelurilor și performanța echipei.",
      trendTitle: "Evoluție Scor Mediu (6 luni)",
      trendDesc: "Trendul scorului mediu la nivelul întregii echipe.",
      volumeTitle: "Volum Evaluări",
      volumeDesc: "Numărul de evaluări realizate în ultimele luni.",
      sectionsTitle: "Performanță pe secțiuni",
      sectionsDesc: "Scorul mediu global pentru fiecare etapă a interacțiunii.",
      avgScore: "Scor Mediu",
      evalCount: "Număr Evaluări",
      scoreLabel: "Scor (%)",
      teamReport: "Raport Echipă",
      teamReportDesc: "Statistici agregate pentru toată echipa",
      individualReport: "Raport Individual",
      individualReportDesc: "Statistici detaliate pentru un specialist",
      generate: "Generează",
      period: "Perioadă",
      from: "De la",
      to: "Până la",
      selectSpecialist: "Selectează specialist",
      print: "Printează / Export PDF",
      topPerformers: "Top specialiști (≥ 80 pct)",
      allSpecialists: "Toți specialiștii",
      noEvals: "Nu există evaluări finalizate în această perioadă.",
      noPeriod: "Completați perioada și apăsați Generează.",
      minScore: "Scor minim",
      maxScore: "Scor maxim",
      monthlyBreakdown: "Evoluție lunară",
      evaluationsList: "Lista evaluărilor",
      generatedOn: "Generat la",
      teamReportTitle: "Raport Performanță Echipă",
      individualReportTitle: "Raport Individual",
      rank: "Loc",
      specialist: "Specialist",
      evaluations: "Evaluări",
      score: "Scor mediu",
      scoreMin: "Min",
      scoreMax: "Max",
      month: "Lună",
      count: "Nr. evaluări",
      date: "Data",
      client: "Client",
      type: "Tip",
      totalScore: "Scor total",
      excellent: "Excelent",
      good: "Bun",
      poor: "Slab",
    },
    settings: {
      title: "Setări",
      subtitle: "Configurați aplicația.",
      criteria: "Editează criterii",
      criteriaDesc: "Gestionați compartimentele și criteriile de evaluare.",
      language: "Limbă interfață",
      languageDesc: "Selectați limba pentru interfața aplicației.",
      addSection: "Compartiment nou",
      sectionName: "Denumire compartiment",
      addCriterion: "Criteriu nou",
      criterionName: "Denumire criteriu",
      weight: "Pontaj",
      save: "Salvează",
      deleteSection: "Șterge compartimentul",
      deleteSectionDesc: "Se vor șterge și toate criteriile din acest compartiment.",
      deleteCriterion: "Șterge criteriul?",
      totalWeight: "Pontaj total",
      rename: "Redenumire",
    },
    common: {
      save: "Salvează",
      cancel: "Anulare",
      delete: "Șterge",
      edit: "Editează",
      add: "Adaugă",
      loading: "Se încarcă...",
      noData: "Nu există date.",
      confirm: "Confirmă",
      na: "N/A",
      back: "Înapoi",
    },
  },

  ru: {
    nav: {
      dashboard: "Дашборд",
      specialists: "Специалисты",
      evaluations: "Оценки",
      reports: "Отчёты",
      settings: "Настройки",
      logout: "Выйти",
    },
    dashboard: {
      title: "Дашборд",
      subtitle: "Обзор показателей команды.",
      totalEvals: "Всего оценок",
      avgScore: "Средний балл команды",
      weakestSection: "Слабейший этап",
      bestSection: "Лучший этап",
      monthlyTrend: "Ежемесячная динамика",
      recentEvals: "Последние оценки",
      recentDesc: "Последние",
      recentDesc2: "добавленных оценок.",
      sectionPerformance: "Результаты по разделам",
      noData: "Недостаточно данных.",
      noRecent: "Последних оценок нет.",
      monthlyProgress: "Прогресс за месяц",
      target: "Цель",
      evalsPerMonth: "оценок/месяц",
      from: "С",
      to: "По",
      trendFrom: "С",
      trendTo: "По",
      noDataInterval: "Нет данных за выбранный период.",
      editTarget: "Изменить месячную цель",
      setTarget: "Установите месячную цель",
      lowPerformers: "Специалисты со средним баллом < 70",
      noLowPerformers: "Специалистов ниже нормы нет.",
      allEvals: "Все оценки",
      noEvalsInterval: "За выбранный период оценок нет.",
      noChanges: "Без изменений",
      score: "Балл",
    },
    specialists: {
      title: "Специалисты",
      subtitle: "Управляйте командой специалистов.",
      add: "Добавить специалиста",
      archiveBtn: "Архивные",
      archived: "В архиве",
      active: "Активные",
      noSpecialists: "Специалисты не найдены.",
      profile: "Профиль",
      evaluate: "Оценить",
      name: "Имя",
      position: "Должность",
      department: "Отдел",
      spiScore: "Балл SPI",
      evals: "Оценок",
      status: "Статус",
      actions: "Действия",
      archiveConfirm: "Архивировать специалиста?",
      archiveDesc: "Специалист будет перемещён в архив и не будет отображаться в активных списках.",
      firstName: "Имя",
      lastName: "Фамилия",
      cancel: "Отмена",
      save: "Сохранить",
      addTitle: "Добавить нового специалиста",
    },
    evaluations: {
      title: "Оценки",
      subtitle: "Список всех оценок в системе.",
      new: "Новая оценка",
      specialist: "Специалист",
      dateTime: "Дата и время",
      client: "Клиент",
      type: "Тип",
      status: "Статус",
      score: "Балл",
      view: "Просмотр",
      edit: "Изменить",
      delete: "Удалить",
      finalized: "Завершено",
      draft: "Черновик",
      noEvals: "Оценки не найдены.",
      search: "Поиск по специалисту или клиенту...",
      deleteConfirm: "Удалить оценку?",
      deleteDesc: "Это действие необратимо. Черновик оценки для",
      deleteDesc2: "будет удалён.",
      cancel: "Отмена",
      excellent: "Отлично",
      good: "Хорошо",
      poor: "Слабо",
    },
    newEval: {
      title: "Новая оценка",
      editTitle: "Редактировать черновик",
      details: "Детали звонка / встречи",
      specialistLabel: "Специалист *",
      clientLabel: "Клиент *",
      dateLabel: "Дата",
      timeLabel: "Время",
      typeLabel: "Тип оценки",
      evaluatorLabel: "Оценщик",
      typeCall: "Звонок",
      typeMeeting: "Встреча",
      typeChat: "Чат",
      clientPlaceholder: "Имя клиента",
      criteriaTitle: "Критерии оценки",
      weight: "Вес",
      scoreCard: "Балл оценки",
      total: "Итого",
      excellent: "Отлично",
      good: "Хорошо",
      poor: "Слабо",
      levelGood: "Хорошо (100%)",
      levelMedium: "Средне (60%)",
      levelPoor: "Слабо (0%)",
      observations: "Наблюдения (необязательно)",
      audio: "Прикрепить запись (необязательно)",
      selectAudio: "Выбрать аудиофайл",
      finalize: "Завершить оценку",
      saveDraft: "Сохранить черновик",
      saveChanges: "Сохранить изменения",
      leaveTitle: "Покинуть страницу?",
      leaveDesc: "Все несохранённые данные будут потеряны.",
      leave: "Покинуть",
      cancel: "Отмена",
      requiredFields: "Заполните обязательные поля",
      requiredDesc: "Специалист и клиент обязательны.",
      audioError: "Не удалось прикрепить аудио",
      saveError: "Ошибка сохранения",
      saveErrorDesc: "Пожалуйста, попробуйте снова.",
      finalized: "Оценка завершена",
      draftSaved: "Черновик сохранён",
      selectSpecialist: "Выберите специалиста",
      obtainedScore: "Полученный балл",
    },
    evalDetail: {
      title: "Детали оценки",
      finalized: "Завершена",
      draft: "Черновик",
      specialist: "Специалист",
      evaluator: "Оценщик",
      date: "Дата",
      clientType: "Клиент / Тип",
      audio: "Аудиозапись",
      totalScore: "Общий балл",
      criteria: "Оцениваемые критерии",
      levelGood: "Хорошо (100%)",
      levelMedium: "Средне (60%)",
      levelPoor: "Слабо (0%)",
      weight: "Вес",
      obtainedScore: "Полученный балл",
      observations: "Наблюдения",
      editDraft: "Редактировать черновик",
      unavailable: "Оценка недоступна",
      excellent: "Отлично",
      good: "Хорошо",
      poor: "Слабо",
      average: "среднее",
    },
    profile: {
      avgScore: "Средний балл",
      evalCount: "Количество оценок",
      bestSection: "Лучший этап",
      worstSection: "Слабейший этап",
      evolution: "Динамика (6 месяцев)",
      skills: "Компетенции",
      spiScore: "Балл SPI",
      evaluate: "Оценить",
      history: "История оценок",
      historyDesc: "Все оценки для",
      noEvals: "Оценок не зарегистрировано.",
      noData: "Нет данных.",
      radarMin: "Для радарной диаграммы необходимо не менее 3 категорий.",
      date: "Дата",
      client: "Клиент",
      type: "Тип",
      status: "Статус",
      finalized: "Завершено",
      draft: "Черновик",
      excellent: "Отлично",
      good: "Хорошо",
      poor: "Слабо",
      score: "Балл",
    },
    reports: {
      title: "Отчёты и аналитика",
      subtitle: "Детальная статистика по качеству звонков и эффективности команды.",
      trendTitle: "Динамика среднего балла (6 месяцев)",
      trendDesc: "Тренд среднего балла по всей команде.",
      volumeTitle: "Объём оценок",
      volumeDesc: "Количество оценок за последние месяцы.",
      sectionsTitle: "Результаты по разделам",
      sectionsDesc: "Средний глобальный балл для каждого этапа взаимодействия.",
      avgScore: "Средний балл",
      evalCount: "Количество оценок",
      scoreLabel: "Балл (%)",
      teamReport: "Отчёт по команде",
      teamReportDesc: "Сводная статистика по всей команде",
      individualReport: "Индивидуальный отчёт",
      individualReportDesc: "Детальная статистика по специалисту",
      generate: "Сформировать",
      period: "Период",
      from: "С",
      to: "По",
      selectSpecialist: "Выберите специалиста",
      print: "Печать / Экспорт PDF",
      topPerformers: "Лучшие специалисты (≥ 80 баллов)",
      allSpecialists: "Все специалисты",
      noEvals: "Нет завершённых оценок за этот период.",
      noPeriod: "Заполните период и нажмите Сформировать.",
      minScore: "Мин. балл",
      maxScore: "Макс. балл",
      monthlyBreakdown: "Ежемесячная динамика",
      evaluationsList: "Список оценок",
      generatedOn: "Сформировано",
      teamReportTitle: "Отчёт об эффективности команды",
      individualReportTitle: "Индивидуальный отчёт",
      rank: "Место",
      specialist: "Специалист",
      evaluations: "Оценок",
      score: "Средний балл",
      scoreMin: "Мин",
      scoreMax: "Макс",
      month: "Месяц",
      count: "Кол-во оценок",
      date: "Дата",
      client: "Клиент",
      type: "Тип",
      totalScore: "Общий балл",
      excellent: "Отлично",
      good: "Хорошо",
      poor: "Слабо",
    },
    settings: {
      title: "Настройки",
      subtitle: "Настройка приложения.",
      criteria: "Редактировать критерии",
      criteriaDesc: "Управляйте разделами и критериями оценки.",
      language: "Язык интерфейса",
      languageDesc: "Выберите язык интерфейса приложения.",
      addSection: "Новый раздел",
      sectionName: "Название раздела",
      addCriterion: "Новый критерий",
      criterionName: "Название критерия",
      weight: "Вес",
      save: "Сохранить",
      deleteSection: "Удалить раздел",
      deleteSectionDesc: "Все критерии этого раздела также будут удалены.",
      deleteCriterion: "Удалить критерий?",
      totalWeight: "Общий вес",
      rename: "Переименовать",
    },
    common: {
      save: "Сохранить",
      cancel: "Отмена",
      delete: "Удалить",
      edit: "Изменить",
      add: "Добавить",
      loading: "Загрузка...",
      noData: "Нет данных.",
      confirm: "Подтвердить",
      na: "Н/Д",
      back: "Назад",
    },
  },

  en: {
    nav: {
      dashboard: "Dashboard",
      specialists: "Specialists",
      evaluations: "Evaluations",
      reports: "Reports",
      settings: "Settings",
      logout: "Logout",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Overview of team performance.",
      totalEvals: "Total evaluations",
      avgScore: "Team average score",
      weakestSection: "Weakest stage",
      bestSection: "Best stage",
      monthlyTrend: "Monthly trend",
      recentEvals: "Recent evaluations",
      recentDesc: "Last",
      recentDesc2: "evaluations added.",
      sectionPerformance: "Performance by section",
      noData: "Not enough data.",
      noRecent: "No recent evaluations.",
      monthlyProgress: "Monthly progress",
      target: "Target",
      evalsPerMonth: "evals/month",
      from: "From",
      to: "To",
      trendFrom: "From",
      trendTo: "To",
      noDataInterval: "No data in the selected range.",
      editTarget: "Edit monthly target",
      setTarget: "Set monthly target",
      lowPerformers: "Specialists with avg score < 70",
      noLowPerformers: "No underperforming specialists.",
      allEvals: "All evaluations",
      noEvalsInterval: "No evaluations in the selected range.",
      noChanges: "No changes",
      score: "Score",
    },
    specialists: {
      title: "Specialists",
      subtitle: "Manage your team of specialists.",
      add: "Add specialist",
      archiveBtn: "Archived",
      archived: "Archived",
      active: "Active",
      noSpecialists: "No specialists found.",
      profile: "Profile",
      evaluate: "Evaluate",
      name: "Name",
      position: "Position",
      department: "Department",
      spiScore: "SPI Score",
      evals: "Evaluations",
      status: "Status",
      actions: "Actions",
      archiveConfirm: "Archive specialist?",
      archiveDesc: "The specialist will be moved to the archive and will no longer appear in active lists.",
      firstName: "First name",
      lastName: "Last name",
      cancel: "Cancel",
      save: "Save",
      addTitle: "Add new specialist",
    },
    evaluations: {
      title: "Evaluations",
      subtitle: "List of all evaluations in the system.",
      new: "New evaluation",
      specialist: "Specialist",
      dateTime: "Date & Time",
      client: "Client",
      type: "Type",
      status: "Status",
      score: "Score",
      view: "View",
      edit: "Edit",
      delete: "Delete",
      finalized: "Finalized",
      draft: "Draft",
      noEvals: "No evaluations found.",
      search: "Search by specialist or client...",
      deleteConfirm: "Delete evaluation?",
      deleteDesc: "This action is irreversible. The draft evaluation for",
      deleteDesc2: "will be permanently deleted.",
      cancel: "Cancel",
      excellent: "Excellent",
      good: "Good",
      poor: "Poor",
    },
    newEval: {
      title: "New evaluation",
      editTitle: "Edit draft",
      details: "Call / meeting details",
      specialistLabel: "Specialist *",
      clientLabel: "Client *",
      dateLabel: "Date",
      timeLabel: "Time",
      typeLabel: "Evaluation type",
      evaluatorLabel: "Evaluator",
      typeCall: "Call",
      typeMeeting: "Meeting",
      typeChat: "Chat",
      clientPlaceholder: "Client name",
      criteriaTitle: "Evaluation criteria",
      weight: "Weight",
      scoreCard: "Evaluation score",
      total: "Total",
      excellent: "Excellent",
      good: "Good",
      poor: "Poor",
      levelGood: "Good (100%)",
      levelMedium: "Medium (60%)",
      levelPoor: "Poor (0%)",
      observations: "Observations (optional)",
      audio: "Attach recording (optional)",
      selectAudio: "Select audio file",
      finalize: "Finalize evaluation",
      saveDraft: "Save draft",
      saveChanges: "Save changes",
      leaveTitle: "Leave page?",
      leaveDesc: "All unsaved data will be lost.",
      leave: "Leave",
      cancel: "Cancel",
      requiredFields: "Fill in required fields",
      requiredDesc: "Specialist and client are required.",
      audioError: "Audio could not be attached",
      saveError: "Save error",
      saveErrorDesc: "Please try again.",
      finalized: "Evaluation finalized",
      draftSaved: "Draft saved",
      selectSpecialist: "Select specialist",
      obtainedScore: "Obtained score",
    },
    evalDetail: {
      title: "Evaluation details",
      finalized: "Finalized",
      draft: "Draft",
      specialist: "Specialist",
      evaluator: "Evaluator",
      date: "Date",
      clientType: "Client / Type",
      audio: "Audio recording",
      totalScore: "Total Score",
      criteria: "Evaluated criteria",
      levelGood: "Good (100%)",
      levelMedium: "Medium (60%)",
      levelPoor: "Poor (0%)",
      weight: "Weight",
      obtainedScore: "Obtained score",
      observations: "Observations",
      editDraft: "Edit draft",
      unavailable: "Evaluation unavailable",
      excellent: "Excellent",
      good: "Good",
      poor: "Poor",
      average: "average",
    },
    profile: {
      avgScore: "Average score",
      evalCount: "Number of evaluations",
      bestSection: "Best stage",
      worstSection: "Weakest stage",
      evolution: "Trend (6 months)",
      skills: "Skills",
      spiScore: "SPI Score",
      evaluate: "Evaluate",
      history: "Evaluation history",
      historyDesc: "All evaluations for",
      noEvals: "No evaluations recorded.",
      noData: "No data.",
      radarMin: "At least 3 categories are required for the radar chart.",
      date: "Date",
      client: "Client",
      type: "Type",
      status: "Status",
      finalized: "Finalized",
      draft: "Draft",
      excellent: "Excellent",
      good: "Good",
      poor: "Poor",
      score: "Score",
    },
    reports: {
      title: "Reports & Analytics",
      subtitle: "Detailed statistics on call quality and team performance.",
      trendTitle: "Average Score Trend (6 months)",
      trendDesc: "Average score trend across the entire team.",
      volumeTitle: "Evaluation Volume",
      volumeDesc: "Number of evaluations conducted in recent months.",
      sectionsTitle: "Performance by sections",
      sectionsDesc: "Global average score for each interaction stage.",
      avgScore: "Average Score",
      evalCount: "Evaluations",
      scoreLabel: "Score (%)",
      teamReport: "Team Report",
      teamReportDesc: "Aggregated statistics for the whole team",
      individualReport: "Individual Report",
      individualReportDesc: "Detailed statistics for one specialist",
      generate: "Generate",
      period: "Period",
      from: "From",
      to: "To",
      selectSpecialist: "Select specialist",
      print: "Print / Export PDF",
      topPerformers: "Top performers (≥ 80 pts)",
      allSpecialists: "All specialists",
      noEvals: "No finalized evaluations in this period.",
      noPeriod: "Fill in the period and click Generate.",
      minScore: "Min score",
      maxScore: "Max score",
      monthlyBreakdown: "Monthly breakdown",
      evaluationsList: "Evaluations list",
      generatedOn: "Generated on",
      teamReportTitle: "Team Performance Report",
      individualReportTitle: "Individual Report",
      rank: "Rank",
      specialist: "Specialist",
      evaluations: "Evaluations",
      score: "Avg score",
      scoreMin: "Min",
      scoreMax: "Max",
      month: "Month",
      count: "Count",
      date: "Date",
      client: "Client",
      type: "Type",
      totalScore: "Total score",
      excellent: "Excellent",
      good: "Good",
      poor: "Poor",
    },
    settings: {
      title: "Settings",
      subtitle: "Configure the application.",
      criteria: "Edit criteria",
      criteriaDesc: "Manage sections and evaluation criteria.",
      language: "Interface language",
      languageDesc: "Select the language for the application interface.",
      addSection: "New section",
      sectionName: "Section name",
      addCriterion: "New criterion",
      criterionName: "Criterion name",
      weight: "Weight",
      save: "Save",
      deleteSection: "Delete section",
      deleteSectionDesc: "All criteria in this section will also be deleted.",
      deleteCriterion: "Delete criterion?",
      totalWeight: "Total weight",
      rename: "Rename",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      loading: "Loading...",
      noData: "No data.",
      confirm: "Confirm",
      na: "N/A",
      back: "Back",
    },
  },
} as const;

type Translations = typeof translations.ro;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const LANGUAGE_KEY = "spi_language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANGUAGE_KEY);
    return (saved as Language) || "ro";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_KEY, lang);
  };

  const t = translations[language] as Translations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
